# Generated by Django 2.1.4 on 2018-12-20 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20181220_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='image',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='text',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='video',
            name='owner',
        ),
        migrations.AddField(
            model_name='file',
            name='module',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='file_related', to='courses.Module'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='module',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='image_related', to='courses.Module'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='text_related', to='courses.Module'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='video_related', to='courses.Module'),
            preserve_default=False,
        ),
    ]
