# Generated by Django 2.1.4 on 2018-12-20 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20181220_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('file', models.FileField(upload_to='files')),
                ('video', models.URLField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_related', to='courses.Module')),
            ],
        ),
        migrations.RemoveField(
            model_name='file',
            name='module',
        ),
        migrations.RemoveField(
            model_name='image',
            name='module',
        ),
        migrations.RemoveField(
            model_name='text',
            name='module',
        ),
        migrations.RemoveField(
            model_name='video',
            name='module',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
