# Generated by Django 2.1.4 on 2018-12-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20181220_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='file',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
    ]
