# Generated by Django 2.1.4 on 2018-12-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20181220_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='file',
            field=models.FileField(blank=True, max_length=500, upload_to='files/'),
        ),
    ]
