# Generated by Django 2.1.4 on 2018-12-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20181220_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='file',
        ),
        migrations.AddField(
            model_name='module',
            name='file',
            field=models.FileField(blank=True, upload_to='files'),
        ),
    ]
